### ISSUE TITLE
SAMD51 NVM cache disable before write

### ISSUE THREAD

**Issue by dhalbert** [cmaglie/FlashStorage#37]
@mitchellpontague @cmaglie 

I didn't have a chance to look at #27 before it was merged. Here is one comment.

This erratum says you need to disable the NVM cache before writing to the Page Buffer, for Rev A EFP and Rev D chips. EDIT: incorrect: it's functional in our code: ~~I had misinterpreted the erratum as applicable to old Rev A chips only and had commented this out in our code. In practice I haven't seen this issue, but better safe than sorry.~~

![image](https://user-images.githubusercontent.com/2847802/78262522-ae9f9380-74ce-11ea-99c5-dfb54a87b703.png)

**Comment by cmaglie** [comment]
Thanks @dhalbert this explains why #27 wasn't working when cache is enabled.
Do you have a patch for that already?

**Comment by dhalbert** [comment]
There are two caches: the CMCC cache and the NVMCTRL cache. The NVMCTRL cache is enabled on reset; the CMCC cache is disabled on reset.

I'll do some testing to confirm which affects this. We are turning off the NVMCTRL cache in the UF2 bootloader before writing. We don't enable the CMCC cache in the UF2 bootloader, but we do in CircuitPython.
