### ISSUE TITLE
Compile error for feather m4

### ISSUE THREAD

**Issue by orhanyor** [cmaglie/FlashStorage#43]
Hello. older version used to work but the newer one does not allow me to upload a sketch. here is what i get as an error:

```
Documents\Arduino\libraries\FlashStorage\src\FlashStorage.cpp: In function 'void invalidate_CMCC_cache()':

Documents\Arduino\libraries\FlashStorage\src\FlashStorage.cpp:56:13: error: 'struct Cmcc' has no member named 'CR'; did you mean 'SR'?

   if (CMCC->CR.bit.CSTS) {

             ^~

             SR
```
i modified CR.bit.CSTS to SR.bit.CSTS and it seems to work ok (example sketch works). is that allright or theres something else is going on. thanks

**Comment by dhalbert** [comment]
Same as #46.
