### ISSUE TITLE
Is this library compatible with MKR1000?

### ISSUE THREAD

**Issue by q2dg** [cmaglie/FlashStorage#5]
I suppose this, but I don't know...If it is, maybe Readme.md should reflect it.
Thanks!

**Comment by javorosas** [comment]
I just tested the second example with the MKR1000 and it works like a charm :D

**Comment by cmaglie** [comment]
> If it is, maybe Readme.md should reflect it.

It would be nice also to actually *have* a Readme.me at all :-)
I'm working on it....
